server {
    listen 80;
    location / {
        proxy_pass http://home:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl;
    ssl_certificate /run/secrets/nginx_crt;
    ssl_certificate_key /run/secrets/nginx_key;
    location / {
        proxy_pass http://home:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
