name: Deploy www.starbug.com with Docker Compose

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # 1. Get the current GitHub Runner's public IP
      - name: Get Public IP
        id: ip
        run: |
          ipv4=$(curl --silent https://api.ipify.org)
          echo "ipv4=$ipv4" >> $GITHUB_OUTPUT

      # 2. Open port 22 on using AWS CLI
      - name: Whitelist Runner IP
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            INSTALL_ROOT=/opt/starbug
            if [ ! -d "$INSTALL_ROOT" ]; then
              mkdir -p $INSTALL_ROOT
            fi
            STARBUG_DIR=$INSTALL_ROOT/www_starbug_com
            DEPLOY_BRANCH=deploy
            if [ -d "$STARBUG_DIR" ]; then
              echo "Directory ${{ github.repository  }} exists, pulling latest changes..."
              cd $STARBUG_DIR
              git fetch --all
              git reset --hard origin/deploy
            else
              cd $INSTALL_ROOT
              echo "Directory ${{ github.repository  }} does not exist, cloning repository..."
              git clone https://github.com/${{ github.repository  }}.git $STARBUG_DIR
              cd $STARBUG_DIR
              git checkout $DEPLOY_BRANCH
            fi
            CERTS_DIR=$STARBUG_DIR/nginx/certs
            if [ ! -d "$CERTS_DIR" ]; then
              mkdir -p $CERTS_DIR
            fi
            echo "${{ secrets.NGINX_CRT }}" > $CERTS_DIR/starbug.selfsigned.crt
            echo "${{ secrets.NGINX_KEY }}" > $CERTS_DIR/starbug.selfsigned.key
            echo "${{ secrets.NGINX_DHPARAM }}" > $CERTS_DIR/dhparam.pem
            echo "Starting Docker Compose deployment..."
            docker compose -f 'docker-compose.yml' up -d --build --remove-orphans

      # 3. Remove the IP from the firewall after deployment
      - name: Remove Runner IP from Firewall
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          VITE_ALLOWED_HOSTS: ${{ secrets.VITE_ALLOWED_HOSTS }}
